/**
 * Seed data for the internal royalty-free music catalog.
 *
 * This data is loaded into the `music_tracks` table on first deploy via
 * the migration or a one-shot seed script.
 *
 * Audio files are hosted on R2 at `zoiko-music/{trackId}.mp3`.
 * In development, a script downloads/creates placeholder audio if missing.
 *
 * For production, replace `audioUrl`/`previewUrl` with actual R2 signed URLs
 * pointing to the rendered audio files.
 */

export interface SeedTrack {
  title: string
  artist: string
  album: string | null
  genre: string
  mood: string
  category: string
  durationMs: number
  coverUrl: string | null
  previewUrl: string | null
  audioUrl: string
  license: string
  attribution: string | null
  isActive: boolean
}

const BASE_AUDIO = 'https://cdn.zoikosocial.com/music'
const BASE_COVER = 'https://cdn.zoikosocial.com/music/covers'

export const SEED_TRACKS: SeedTrack[] = [
  // ── Pets & Animals ──────────────────────────────────────────────────────
  {
    title: 'Playful Paws',
    artist: 'Zoiko Audio',
    album: 'Pet Vibes',
    genre: 'Acoustic',
    mood: 'happy',
    category: 'pets',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/playful-paws.jpg`,
    previewUrl: `${BASE_AUDIO}/playful-paws-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/playful-paws.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Whisker Waltz',
    artist: 'Zoiko Audio',
    album: 'Pet Vibes',
    genre: 'Orchestral',
    mood: 'calm',
    category: 'pets',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/whisker-waltz.jpg`,
    previewUrl: `${BASE_AUDIO}/whisker-waltz-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/whisker-waltz.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Happy Tails',
    artist: 'Zoiko Audio',
    album: 'Pet Vibes',
    genre: 'Folk',
    mood: 'happy',
    category: 'pets',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/happy-tails.jpg`,
    previewUrl: `${BASE_AUDIO}/happy-tails-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/happy-tails.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Catnap Serenade',
    artist: 'Zoiko Audio',
    album: 'Pet Vibes',
    genre: 'Ambient',
    mood: 'calm',
    category: 'pets',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/catnap-serenade.jpg`,
    previewUrl: `${BASE_AUDIO}/catnap-serenade-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/catnap-serenade.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Happy & Upbeat ──────────────────────────────────────────────────────
  {
    title: 'Sunshine Stroll',
    artist: 'Zoiko Audio',
    album: 'Happy Days',
    genre: 'Pop',
    mood: 'happy',
    category: 'happy',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/sunshine-stroll.jpg`,
    previewUrl: `${BASE_AUDIO}/sunshine-stroll-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/sunshine-stroll.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Bubblegum Beat',
    artist: 'Zoiko Audio',
    album: 'Happy Days',
    genre: 'Electronic',
    mood: 'happy',
    category: 'happy',
    durationMs: 25_000,
    coverUrl: `${BASE_COVER}/bubblegum-beat.jpg`,
    previewUrl: `${BASE_AUDIO}/bubblegum-beat-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/bubblegum-beat.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Good Morning Glow',
    artist: 'Zoiko Audio',
    album: 'Happy Days',
    genre: 'Acoustic',
    mood: 'happy',
    category: 'happy',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/good-morning-glow.jpg`,
    previewUrl: `${BASE_AUDIO}/good-morning-glow-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/good-morning-glow.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Calm & Relaxing ─────────────────────────────────────────────────────
  {
    title: 'Gentle Rain',
    artist: 'Zoiko Audio',
    album: 'Calm Waters',
    genre: 'Ambient',
    mood: 'calm',
    category: 'calm',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/gentle-rain.jpg`,
    previewUrl: `${BASE_AUDIO}/gentle-rain-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/gentle-rain.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Ocean Breath',
    artist: 'Zoiko Audio',
    album: 'Calm Waters',
    genre: 'Ambient',
    mood: 'calm',
    category: 'calm',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/ocean-breath.jpg`,
    previewUrl: `${BASE_AUDIO}/ocean-breath-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/ocean-breath.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Forest Whispers',
    artist: 'Zoiko Audio',
    album: 'Calm Waters',
    genre: 'Nature',
    mood: 'calm',
    category: 'calm',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/forest-whispers.jpg`,
    previewUrl: `${BASE_AUDIO}/forest-whispers-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/forest-whispers.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Cinematic & Emotional ───────────────────────────────────────────────
  {
    title: 'Epic Horizons',
    artist: 'Zoiko Audio',
    album: 'Cinematic Collection',
    genre: 'Orchestral',
    mood: 'cinematic',
    category: 'cinematic',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/epic-horizons.jpg`,
    previewUrl: `${BASE_AUDIO}/epic-horizons-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/epic-horizons.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Rising Tide',
    artist: 'Zoiko Audio',
    album: 'Cinematic Collection',
    genre: 'Orchestral',
    mood: 'cinematic',
    category: 'cinematic',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/rising-tide.jpg`,
    previewUrl: `${BASE_AUDIO}/rising-tide-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/rising-tide.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Heartstrings',
    artist: 'Zoiko Audio',
    album: 'Cinematic Collection',
    genre: 'Piano',
    mood: 'emotional',
    category: 'emotional',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/heartstrings.jpg`,
    previewUrl: `${BASE_AUDIO}/heartstrings-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/heartstrings.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Golden Hour',
    artist: 'Zoiko Audio',
    album: 'Cinematic Collection',
    genre: 'Ambient',
    mood: 'emotional',
    category: 'emotional',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/golden-hour.jpg`,
    previewUrl: `${BASE_AUDIO}/golden-hour-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/golden-hour.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Tender Moments',
    artist: 'Zoiko Audio',
    album: 'Cinematic Collection',
    genre: 'Piano',
    mood: 'emotional',
    category: 'emotional',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/tender-moments.jpg`,
    previewUrl: `${BASE_AUDIO}/tender-moments-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/tender-moments.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Travel & Adventure ──────────────────────────────────────────────────
  {
    title: 'Wanderlust',
    artist: 'Zoiko Audio',
    album: 'Travel Beats',
    genre: 'Indie Folk',
    mood: 'travel',
    category: 'travel',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/wanderlust.jpg`,
    previewUrl: `${BASE_AUDIO}/wanderlust-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/wanderlust.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Road Trip',
    artist: 'Zoiko Audio',
    album: 'Travel Beats',
    genre: 'Rock',
    mood: 'happy',
    category: 'travel',
    durationMs: 25_000,
    coverUrl: `${BASE_COVER}/road-trip.jpg`,
    previewUrl: `${BASE_AUDIO}/road-trip-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/road-trip.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Coastal Drive',
    artist: 'Zoiko Audio',
    album: 'Travel Beats',
    genre: 'Electronic',
    mood: 'happy',
    category: 'travel',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/coastal-drive.jpg`,
    previewUrl: `${BASE_AUDIO}/coastal-drive-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/coastal-drive.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Nature & Outdoors ───────────────────────────────────────────────────
  {
    title: 'Morning Dew',
    artist: 'Zoiko Audio',
    album: 'Nature Sounds',
    genre: 'Ambient',
    mood: 'nature',
    category: 'nature',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/morning-dew.jpg`,
    previewUrl: `${BASE_AUDIO}/morning-dew-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/morning-dew.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Mountain Trail',
    artist: 'Zoiko Audio',
    album: 'Nature Sounds',
    genre: 'Folk',
    mood: 'nature',
    category: 'nature',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/mountain-trail.jpg`,
    previewUrl: `${BASE_AUDIO}/mountain-trail-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/mountain-trail.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Funny & Playful ─────────────────────────────────────────────────────
  {
    title: 'Giggles',
    artist: 'Zoiko Audio',
    album: 'Playful Tunes',
    genre: 'Novelty',
    mood: 'funny',
    category: 'funny',
    durationMs: 20_000,
    coverUrl: `${BASE_COVER}/giggles.jpg`,
    previewUrl: `${BASE_AUDIO}/giggles-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/giggles.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Goofy Groove',
    artist: 'Zoiko Audio',
    album: 'Playful Tunes',
    genre: 'Jazz',
    mood: 'funny',
    category: 'funny',
    durationMs: 20_000,
    coverUrl: `${BASE_COVER}/goofy-groove.jpg`,
    previewUrl: `${BASE_AUDIO}/goofy-groove-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/goofy-groove.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Silly Walk',
    artist: 'Zoiko Audio',
    album: 'Playful Tunes',
    genre: 'Novelty',
    mood: 'funny',
    category: 'funny',
    durationMs: 20_000,
    coverUrl: `${BASE_COVER}/silly-walk.jpg`,
    previewUrl: `${BASE_AUDIO}/silly-walk-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/silly-walk.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Inspirational & Uplifting ───────────────────────────────────────────
  {
    title: 'New Dawn',
    artist: 'Zoiko Audio',
    album: 'Inspire',
    genre: 'Orchestral',
    mood: 'inspirational',
    category: 'inspirational',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/new-dawn.jpg`,
    previewUrl: `${BASE_AUDIO}/new-dawn-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/new-dawn.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Unstoppable',
    artist: 'Zoiko Audio',
    album: 'Inspire',
    genre: 'Electronic',
    mood: 'inspirational',
    category: 'inspirational',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/unstoppable.jpg`,
    previewUrl: `${BASE_AUDIO}/unstoppable-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/unstoppable.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Limitless',
    artist: 'Zoiko Audio',
    album: 'Inspire',
    genre: 'Pop',
    mood: 'inspirational',
    category: 'inspirational',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/limitless.jpg`,
    previewUrl: `${BASE_AUDIO}/limitless-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/limitless.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },

  // ── Background & Corporate ──────────────────────────────────────────────
  {
    title: 'Clean Lines',
    artist: 'Zoiko Audio',
    album: 'Background Vol 1',
    genre: 'Electronic',
    mood: 'background',
    category: 'background',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/clean-lines.jpg`,
    previewUrl: `${BASE_AUDIO}/clean-lines-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/clean-lines.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Fresh Start',
    artist: 'Zoiko Audio',
    album: 'Background Vol 1',
    genre: 'Acoustic',
    mood: 'background',
    category: 'background',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/fresh-start.jpg`,
    previewUrl: `${BASE_AUDIO}/fresh-start-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/fresh-start.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Professional Pulse',
    artist: 'Zoiko Audio',
    album: 'Background Vol 1',
    genre: 'Corporate',
    mood: 'corporate',
    category: 'corporate',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/professional-pulse.jpg`,
    previewUrl: `${BASE_AUDIO}/professional-pulse-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/professional-pulse.mp3`,
    license: 'royalty-free',
    attribution: '',
    isActive: true,
  },

  // ── Ambient & Chill ─────────────────────────────────────────────────────
  {
    title: 'Stargazer',
    artist: 'Zoiko Audio',
    album: 'Ambient Dreams',
    genre: 'Ambient',
    mood: 'ambient',
    category: 'ambient',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/stargazer.jpg`,
    previewUrl: `${BASE_AUDIO}/stargazer-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/stargazer.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Lunar Tide',
    artist: 'Zoiko Audio',
    album: 'Ambient Dreams',
    genre: 'Ambient',
    mood: 'ambient',
    category: 'ambient',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/lunar-tide.jpg`,
    previewUrl: `${BASE_AUDIO}/lunar-tide-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/lunar-tide.mp3`,
    license: 'royalty-free',
    attribution: 'Music by Zoiko Audio',
    isActive: true,
  },
  {
    title: 'Deep Focus',
    artist: 'Zoiko Audio',
    album: 'Ambient Dreams',
    genre: 'Ambient',
    mood: 'ambient',
    category: 'ambient',
    durationMs: 30_000,
    coverUrl: `${BASE_COVER}/deep-focus.jpg`,
    previewUrl: `${BASE_AUDIO}/deep-focus-preview.mp3`,
    audioUrl: `${BASE_AUDIO}/deep-focus.mp3`,
    license: 'royalty-free',
    attribution: '',
    isActive: true,
  },
]

/**
 * Generates a SQL migration snippet to seed the music_tracks table.
 * Run this manually as a one-shot seed or include it in a migration.
 */
export function generateSeedInsertSQL(): string {
  const rows = SEED_TRACKS.map(
    (t) =>
      `(
  '${t.title.replace(/'/g, "''")}',
  '${t.artist.replace(/'/g, "''")}',
  ${t.album ? `'${t.album.replace(/'/g, "''")}'` : 'NULL'},
  '${t.genre}',
  '${t.mood}'::music_mood,
  '${t.category}'::music_category,
  ${t.durationMs},
  ${t.coverUrl ? `'${t.coverUrl}'` : 'NULL'},
  ${t.previewUrl ? `'${t.previewUrl}'` : 'NULL'},
  '${t.audioUrl}',
  '${t.license}',
  ${t.attribution ? `'${t.attribution.replace(/'/g, "''")}'` : 'NULL'},
  true
)`,
  )

  return `INSERT INTO music_tracks (title, artist, album, genre, mood, category, duration_ms, cover_url, preview_url, audio_url, license, attribution, is_active)
VALUES\n${rows.join(',\n')};\n`
}
